/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/billing/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SubscriptionDto"];
                        "application/json": components["schemas"]["SubscriptionDto"];
                        "text/json": components["schemas"]["SubscriptionDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CheckoutResponse"];
                        "application/json": components["schemas"]["CheckoutResponse"];
                        "text/json": components["schemas"]["CheckoutResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CheckoutResponse"];
                        "application/json": components["schemas"]["CheckoutResponse"];
                        "text/json": components["schemas"]["CheckoutResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    year?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CalendarEntryDto"][];
                        "application/json": components["schemas"]["CalendarEntryDto"][];
                        "text/json": components["schemas"]["CalendarEntryDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateCalendarEntryRequest"];
                    "text/json": components["schemas"]["CreateCalendarEntryRequest"];
                    "application/*+json": components["schemas"]["CreateCalendarEntryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CalendarEntryDto"];
                        "application/json": components["schemas"]["CalendarEntryDto"];
                        "text/json": components["schemas"]["CalendarEntryDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    year?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DefaultHolidayDto"][];
                        "application/json": components["schemas"]["DefaultHolidayDto"][];
                        "text/json": components["schemas"]["DefaultHolidayDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/calendar/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateCalendarEntryRequest"];
                    "text/json": components["schemas"]["UpdateCalendarEntryRequest"];
                    "application/*+json": components["schemas"]["UpdateCalendarEntryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CalendarEntryDto"];
                        "application/json": components["schemas"]["CalendarEntryDto"];
                        "text/json": components["schemas"]["CalendarEntryDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ClassDto"][];
                        "application/json": components["schemas"]["ClassDto"][];
                        "text/json": components["schemas"]["ClassDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertClassRequest"];
                    "text/json": components["schemas"]["UpsertClassRequest"];
                    "application/*+json": components["schemas"]["UpsertClassRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ClassDto"];
                        "application/json": components["schemas"]["ClassDto"];
                        "text/json": components["schemas"]["ClassDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ClassDto"];
                        "application/json": components["schemas"]["ClassDto"];
                        "text/json": components["schemas"]["ClassDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertClassRequest"];
                    "text/json": components["schemas"]["UpsertClassRequest"];
                    "application/*+json": components["schemas"]["UpsertClassRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ClassDto"];
                        "application/json": components["schemas"]["ClassDto"];
                        "text/json": components["schemas"]["ClassDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseDto"][];
                        "application/json": components["schemas"]["CourseDto"][];
                        "text/json": components["schemas"]["CourseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertCourseRequest"];
                    "text/json": components["schemas"]["UpsertCourseRequest"];
                    "application/*+json": components["schemas"]["UpsertCourseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseDto"];
                        "application/json": components["schemas"]["CourseDto"];
                        "text/json": components["schemas"]["CourseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseDto"];
                        "application/json": components["schemas"]["CourseDto"];
                        "text/json": components["schemas"]["CourseDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertCourseRequest"];
                    "text/json": components["schemas"]["UpsertCourseRequest"];
                    "application/*+json": components["schemas"]["UpsertCourseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseDto"];
                        "application/json": components["schemas"]["CourseDto"];
                        "text/json": components["schemas"]["CourseDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    courseId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FileDto"][];
                        "application/json": components["schemas"]["FileDto"][];
                        "text/json": components["schemas"]["FileDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                        /** Format: uuid */
                        courseId?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FileDto"];
                        "application/json": components["schemas"]["FileDto"];
                        "text/json": components["schemas"]["FileDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/hours/staff.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/hours/courses.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/schema.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoomDto"][];
                        "application/json": components["schemas"]["RoomDto"][];
                        "text/json": components["schemas"]["RoomDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertRoomRequest"];
                    "text/json": components["schemas"]["UpsertRoomRequest"];
                    "application/*+json": components["schemas"]["UpsertRoomRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoomDto"];
                        "application/json": components["schemas"]["RoomDto"];
                        "text/json": components["schemas"]["RoomDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoomDto"];
                        "application/json": components["schemas"]["RoomDto"];
                        "text/json": components["schemas"]["RoomDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertRoomRequest"];
                    "text/json": components["schemas"]["UpsertRoomRequest"];
                    "application/*+json": components["schemas"]["UpsertRoomRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RoomDto"];
                        "application/json": components["schemas"]["RoomDto"];
                        "text/json": components["schemas"]["RoomDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/{staffId}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    staffId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ScheduleSlotDto"][];
                        "application/json": components["schemas"]["ScheduleSlotDto"][];
                        "text/json": components["schemas"]["ScheduleSlotDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rooms/{roomId}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    roomId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ScheduleSlotDto"][];
                        "application/json": components["schemas"]["ScheduleSlotDto"][];
                        "text/json": components["schemas"]["ScheduleSlotDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SchemaDto"][];
                        "application/json": components["schemas"]["SchemaDto"][];
                        "text/json": components["schemas"]["SchemaDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateSchemaRequest"];
                    "text/json": components["schemas"]["CreateSchemaRequest"];
                    "application/*+json": components["schemas"]["CreateSchemaRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SchemaDto"];
                        "application/json": components["schemas"]["SchemaDto"];
                        "text/json": components["schemas"]["SchemaDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/schemas/{schemaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                    schemaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SchemaDetailDto"];
                        "application/json": components["schemas"]["SchemaDetailDto"];
                        "text/json": components["schemas"]["SchemaDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                    schemaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/schemas/{schemaId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                    schemaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SchemaDto"];
                        "application/json": components["schemas"]["SchemaDto"];
                        "text/json": components["schemas"]["SchemaDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/schemas/{schemaId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                    schemaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SchemaDto"];
                        "application/json": components["schemas"]["SchemaDto"];
                        "text/json": components["schemas"]["SchemaDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/schemas/{schemaId}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                    schemaId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CopySchemaRequest"];
                    "text/json": components["schemas"]["CopySchemaRequest"];
                    "application/*+json": components["schemas"]["CopySchemaRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SchemaDto"];
                        "application/json": components["schemas"]["SchemaDto"];
                        "text/json": components["schemas"]["SchemaDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/schemas/{schemaId}/copy-to/{targetClassId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                    schemaId: string;
                    targetClassId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CopySchemaRequest"];
                    "text/json": components["schemas"]["CopySchemaRequest"];
                    "application/*+json": components["schemas"]["CopySchemaRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SchemaDto"];
                        "application/json": components["schemas"]["SchemaDto"];
                        "text/json": components["schemas"]["SchemaDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/schemas/{schemaId}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                    schemaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SlotDto"][];
                        "application/json": components["schemas"]["SlotDto"][];
                        "text/json": components["schemas"]["SlotDto"][];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                    schemaId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertSlotRequest"];
                    "text/json": components["schemas"]["UpsertSlotRequest"];
                    "application/*+json": components["schemas"]["UpsertSlotRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SlotsAndConflictsDto"];
                        "application/json": components["schemas"]["SlotsAndConflictsDto"];
                        "text/json": components["schemas"]["SlotsAndConflictsDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/schemas/{schemaId}/slots/{timeSlotId}/{weekday}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                    schemaId: string;
                    timeSlotId: string;
                    weekday: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SlotsAndConflictsDto"];
                        "application/json": components["schemas"]["SlotsAndConflictsDto"];
                        "text/json": components["schemas"]["SlotsAndConflictsDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/schemas/{schemaId}/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                    schemaId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConflictInfo"][];
                        "application/json": components["schemas"]["ConflictInfo"][];
                        "text/json": components["schemas"]["ConflictInfo"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SchoolSettingsDto"];
                        "application/json": components["schemas"]["SchoolSettingsDto"];
                        "text/json": components["schemas"]["SchoolSettingsDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateSchoolSettingsRequest"];
                    "text/json": components["schemas"]["UpdateSchoolSettingsRequest"];
                    "application/*+json": components["schemas"]["UpdateSchoolSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SchoolSettingsDto"];
                        "application/json": components["schemas"]["SchoolSettingsDto"];
                        "text/json": components["schemas"]["SchoolSettingsDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/onboarding-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["OnboardingStatusDto"];
                        "application/json": components["schemas"]["OnboardingStatusDto"];
                        "text/json": components["schemas"]["OnboardingStatusDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schools/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SchoolSettingsDto"];
                        "application/json": components["schemas"]["SchoolSettingsDto"];
                        "text/json": components["schemas"]["SchoolSettingsDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StaffDto"][];
                        "application/json": components["schemas"]["StaffDto"][];
                        "text/json": components["schemas"]["StaffDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertStaffRequest"];
                    "text/json": components["schemas"]["UpsertStaffRequest"];
                    "application/*+json": components["schemas"]["UpsertStaffRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StaffDto"];
                        "application/json": components["schemas"]["StaffDto"];
                        "text/json": components["schemas"]["StaffDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StaffDto"];
                        "application/json": components["schemas"]["StaffDto"];
                        "text/json": components["schemas"]["StaffDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertStaffRequest"];
                    "text/json": components["schemas"]["UpsertStaffRequest"];
                    "application/*+json": components["schemas"]["UpsertStaffRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StaffDto"];
                        "application/json": components["schemas"]["StaffDto"];
                        "text/json": components["schemas"]["StaffDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff-invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InvitationDto"][];
                        "application/json": components["schemas"]["InvitationDto"][];
                        "text/json": components["schemas"]["InvitationDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff-invitations/by-staff/{staffId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    staffId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InvitationDto"][];
                        "application/json": components["schemas"]["InvitationDto"][];
                        "text/json": components["schemas"]["InvitationDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff-invitations/invite/{staffId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    staffId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InvitationDto"];
                        "application/json": components["schemas"]["InvitationDto"];
                        "text/json": components["schemas"]["InvitationDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff-invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AcceptInvitationRequest"];
                    "text/json": components["schemas"]["AcceptInvitationRequest"];
                    "application/*+json": components["schemas"]["AcceptInvitationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff-invitations/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    token?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DashboardStats"];
                        "application/json": components["schemas"]["DashboardStats"];
                        "text/json": components["schemas"]["DashboardStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stripe/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateTenantRequest"];
                    "text/json": components["schemas"]["CreateTenantRequest"];
                    "application/*+json": components["schemas"]["CreateTenantRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TenantDto"];
                        "application/json": components["schemas"]["TenantDto"];
                        "text/json": components["schemas"]["TenantDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time-slot-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TemplateDto"];
                        "application/json": components["schemas"]["TemplateDto"];
                        "text/json": components["schemas"]["TemplateDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertTemplateRequest"];
                    "text/json": components["schemas"]["UpsertTemplateRequest"];
                    "application/*+json": components["schemas"]["UpsertTemplateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TemplateDto"];
                        "application/json": components["schemas"]["TemplateDto"];
                        "text/json": components["schemas"]["TemplateDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/time-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TimeSlotDto"][];
                        "application/json": components["schemas"]["TimeSlotDto"][];
                        "text/json": components["schemas"]["TimeSlotDto"][];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertTimeSlotRequest"][];
                    "text/json": components["schemas"]["UpsertTimeSlotRequest"][];
                    "application/*+json": components["schemas"]["UpsertTimeSlotRequest"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TimeSlotDto"][];
                        "application/json": components["schemas"]["TimeSlotDto"][];
                        "text/json": components["schemas"]["TimeSlotDto"][];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TimeSlotDto"][];
                        "application/json": components["schemas"]["TimeSlotDto"][];
                        "text/json": components["schemas"]["TimeSlotDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/ugeplan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    isoYear?: number;
                    isoWeek?: number;
                };
                header?: never;
                path: {
                    classId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WeekPlanDto"];
                        "application/json": components["schemas"]["WeekPlanDto"];
                        "text/json": components["schemas"]["WeekPlanDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/ugeplan/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: {
                    isoYear?: number;
                    isoWeek?: number;
                };
                header?: never;
                path: {
                    classId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertWeekPlanSlotRequest"];
                    "text/json": components["schemas"]["UpsertWeekPlanSlotRequest"];
                    "application/*+json": components["schemas"]["UpsertWeekPlanSlotRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WeekPlanSlotDto"];
                        "application/json": components["schemas"]["WeekPlanSlotDto"];
                        "text/json": components["schemas"]["WeekPlanSlotDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/ugeplan/slots/{slotId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                    slotId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AddFileToSlotRequest"];
                    "text/json": components["schemas"]["AddFileToSlotRequest"];
                    "application/*+json": components["schemas"]["AddFileToSlotRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WeekPlanSlotFileDto"];
                        "application/json": components["schemas"]["WeekPlanSlotFileDto"];
                        "text/json": components["schemas"]["WeekPlanSlotFileDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{classId}/ugeplan/slots/{slotId}/files/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    classId: string;
                    slotId: string;
                    fileId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptInvitationRequest: {
            token?: string | null;
            keycloakSubject?: string | null;
        };
        AddFileToSlotRequest: {
            /** Format: uuid */
            schoolFileId?: string;
        };
        BreakDto: {
            /** Format: uuid */
            id?: string;
            /** Format: time */
            startTime?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        CalendarEntryDto: {
            /** Format: uuid */
            id?: string;
            type?: components["schemas"]["CalendarEntryType"];
            title?: string | null;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
        };
        /** @enum {string} */
        CalendarEntryType: "Ferie" | "Lukkedag" | "Arbejdsdag" | "Begivenhed";
        CheckoutResponse: {
            url?: string | null;
        };
        ClassDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            description?: string | null;
        };
        ConflictInfo: {
            type?: components["schemas"]["ConflictType"];
            /** Format: uuid */
            slotAId?: string;
            /** Format: uuid */
            slotBId?: string;
            /** Format: uuid */
            resourceId?: string;
            resourceName?: string | null;
            weekday?: components["schemas"]["DayOfWeek"];
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
        };
        /** @enum {string} */
        ConflictType: "TeacherDoubleBooked" | "RoomDoubleBooked" | "AideDoubleBooked";
        CopySchemaRequest: {
            name?: string | null;
        };
        CourseDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            description?: string | null;
        };
        CreateCalendarEntryRequest: {
            title?: string | null;
            type?: components["schemas"]["CalendarEntryType"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
        };
        CreateSchemaRequest: {
            name?: string | null;
        };
        CreateTenantRequest: {
            name?: string | null;
            contactEmail?: string | null;
        };
        DashboardStats: {
            /** Format: int32 */
            classCount?: number;
            /** Format: int32 */
            staffCount?: number;
            /** Format: int32 */
            courseCount?: number;
            /** Format: int32 */
            roomCount?: number;
            /** Format: int32 */
            schemasComplete?: number;
            /** Format: int32 */
            schemasTotal?: number;
            hoursPerCourse?: components["schemas"]["HoursPerCourse"][] | null;
            hoursPerStaff?: components["schemas"]["HoursPerStaff"][] | null;
            unassignedClasses?: components["schemas"]["UnassignedClass"][] | null;
        };
        /** @enum {string} */
        DayOfWeek: "Sunday" | "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday";
        DefaultHolidayDto: {
            title?: string | null;
            type?: components["schemas"]["CalendarEntryType"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
        };
        FileDto: {
            /** Format: uuid */
            id?: string;
            fileName?: string | null;
            contentType?: string | null;
            /** Format: int64 */
            sizeBytes?: number;
            url?: string | null;
            /** Format: uuid */
            courseId?: string | null;
            courseName?: string | null;
            uploadedBy?: string | null;
            /** Format: date-time */
            uploadedAt?: string;
        };
        HoursPerCourse: {
            /** Format: uuid */
            courseId?: string;
            courseName?: string | null;
            /** Format: uuid */
            classId?: string;
            className?: string | null;
            /** Format: double */
            hours?: number;
        };
        HoursPerStaff: {
            /** Format: uuid */
            staffId?: string;
            staffName?: string | null;
            role?: components["schemas"]["StaffRole"];
            /** Format: double */
            hours?: number;
        };
        InvitationDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            staffId?: string;
            staffName?: string | null;
            email?: string | null;
            status?: string | null;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            acceptedAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        OnboardingStatusDto: {
            hasLogo?: boolean;
            /** Format: int32 */
            staffCount?: number;
            /** Format: int32 */
            classCount?: number;
            /** Format: int32 */
            courseCount?: number;
            /** Format: int32 */
            roomCount?: number;
            /** Format: int32 */
            stepsCompleted?: number;
            /** Format: int32 */
            stepsTotal?: number;
        };
        RoomDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            /** Format: int32 */
            capacity?: number | null;
            description?: string | null;
        };
        ScheduleSlotDto: {
            weekday?: components["schemas"]["DayOfWeek"];
            startTime?: string | null;
            endTime?: string | null;
            courseName?: string | null;
            className?: string | null;
            /** Format: uuid */
            roomId?: string | null;
            roomName?: string | null;
            /** Format: uuid */
            aideId?: string | null;
            aideName?: string | null;
            /** Format: uuid */
            teacherId?: string | null;
            teacherName?: string | null;
        };
        SchemaDetailDto: {
            schema?: components["schemas"]["SchemaDto"];
            slots?: components["schemas"]["SlotDto"][] | null;
            conflicts?: components["schemas"]["ConflictInfo"][] | null;
        };
        SchemaDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            classId?: string;
            name?: string | null;
            status?: components["schemas"]["SchemaStatus"];
            isActive?: boolean;
        };
        /** @enum {string} */
        SchemaStatus: "Draft" | "Complete";
        SchoolSettingsDto: {
            name?: string | null;
            contactEmail?: string | null;
            contactPhone?: string | null;
            logoUrl?: string | null;
        };
        SlotDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            timeSlotId?: string;
            weekday?: components["schemas"]["DayOfWeek"];
            /** Format: uuid */
            courseId?: string;
            courseName?: string | null;
            /** Format: uuid */
            teacherId?: string;
            teacherName?: string | null;
            /** Format: uuid */
            roomId?: string | null;
            roomName?: string | null;
            /** Format: uuid */
            aideId?: string | null;
            aideName?: string | null;
        };
        SlotsAndConflictsDto: {
            slots?: components["schemas"]["SlotDto"][] | null;
            conflicts?: components["schemas"]["ConflictInfo"][] | null;
        };
        StaffDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            email?: string | null;
            phone?: string | null;
            role?: components["schemas"]["StaffRole"];
        };
        /** @enum {string} */
        StaffRole: "Teacher" | "Aide" | "Substitute";
        SubscriptionDto: {
            status?: components["schemas"]["SubscriptionStatus"];
            /** Format: date-time */
            trialEnd?: string;
            /** Format: date-time */
            currentPeriodEnd?: string | null;
            isTrialing?: boolean;
            isActive?: boolean;
            hasAccess?: boolean;
            /** Format: int32 */
            trialDaysLeft?: number;
        };
        /** @enum {string} */
        SubscriptionStatus: "Trialing" | "Active" | "PastDue" | "Canceled" | "Unpaid";
        TemplateDto: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            lessonDurationMinutes?: number;
            /** Format: time */
            dayStartTime?: string;
            /** Format: time */
            dayEndTime?: string;
            activeDays?: string | null;
            breaks?: components["schemas"]["BreakDto"][] | null;
        };
        TenantDto: {
            /** Format: uuid */
            id?: string;
            name?: string | null;
            contactEmail?: string | null;
        };
        TimeSlotDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            classId?: string | null;
            /** Format: int32 */
            sortOrder?: number;
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            label?: string | null;
            isBreak?: boolean;
        };
        UnassignedClass: {
            /** Format: uuid */
            classId?: string;
            className?: string | null;
            /** Format: int32 */
            emptySlots?: number;
            hasSchema?: boolean;
        };
        UpdateCalendarEntryRequest: {
            title?: string | null;
            type?: components["schemas"]["CalendarEntryType"];
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
        };
        UpdateSchoolSettingsRequest: {
            name?: string | null;
            contactEmail?: string | null;
            contactPhone?: string | null;
        };
        UpsertBreakRequest: {
            /** Format: time */
            startTime?: string;
            /** Format: int32 */
            durationMinutes?: number;
        };
        UpsertClassRequest: {
            name?: string | null;
            description?: string | null;
        };
        UpsertCourseRequest: {
            name?: string | null;
            description?: string | null;
        };
        UpsertRoomRequest: {
            name?: string | null;
            /** Format: int32 */
            capacity?: number | null;
            description?: string | null;
        };
        UpsertSlotRequest: {
            /** Format: uuid */
            timeSlotId?: string;
            weekday?: components["schemas"]["DayOfWeek"];
            /** Format: uuid */
            courseId?: string;
            /** Format: uuid */
            teacherId?: string;
            /** Format: uuid */
            roomId?: string | null;
            /** Format: uuid */
            aideId?: string | null;
        };
        UpsertStaffRequest: {
            name?: string | null;
            email?: string | null;
            phone?: string | null;
            role?: components["schemas"]["StaffRole"];
        };
        UpsertTemplateRequest: {
            /** Format: int32 */
            lessonDurationMinutes?: number;
            /** Format: time */
            dayStartTime?: string;
            /** Format: time */
            dayEndTime?: string;
            activeDays?: string | null;
            breaks?: components["schemas"]["UpsertBreakRequest"][] | null;
        };
        UpsertTimeSlotRequest: {
            /** Format: int32 */
            sortOrder?: number;
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            label?: string | null;
        };
        UpsertWeekPlanSlotRequest: {
            /** Format: uuid */
            schemaSlotId?: string;
            beskrivelse?: string | null;
            lektier?: string | null;
            /** Format: uuid */
            fagSwapCourseId?: string | null;
        };
        WeekPlanDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            classId?: string;
            /** Format: int32 */
            isoYear?: number;
            /** Format: int32 */
            isoWeek?: number;
            /** Format: date */
            weekStartDate?: string;
            /** Format: date */
            weekEndDate?: string;
            isHolidayWeek?: boolean;
            holidayTitle?: string | null;
            slots?: components["schemas"]["WeekPlanSlotDto"][] | null;
        };
        WeekPlanSlotDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            schemaSlotId?: string;
            weekday?: components["schemas"]["DayOfWeek"];
            /** Format: uuid */
            timeSlotId?: string;
            timeSlotLabel?: string | null;
            /** Format: time */
            startTime?: string;
            /** Format: time */
            endTime?: string;
            /** Format: uuid */
            courseId?: string;
            courseName?: string | null;
            /** Format: uuid */
            originalCourseId?: string | null;
            originalCourseName?: string | null;
            beskrivelse?: string | null;
            lektier?: string | null;
            files?: components["schemas"]["WeekPlanSlotFileDto"][] | null;
        };
        WeekPlanSlotFileDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            schoolFileId?: string;
            fileName?: string | null;
            url?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
